#!/bin/sh

# [1: install qt-autoconnect]
# give rights to run scripts
chmod +x /opt/qt_autoconnect/scripts/*.sh

# give rights to read logs
chmod 666 /opt/qt_autoconnect/logs/*

# add command shortcut
sudo ln -s /opt/qt_autoconnect/scripts/run.sh /usr/local/bin/qt-autoconnect



# [2: tell user to change its credentials]
echo "You should change your Quantic Telecom credentials
Use flag '-s' with the command 'qt-autoconnect'.
Use flag '--help' for more info.
"



# [3: set up cron routine]


exit 0
